
# cargo-vet audits file

[audits]

[[trusted.autocfg]]
criteria = "safe-to-run"
user-id = 539 # Josh Stone (cuviper)
start = "2019-05-22"
end = "2027-02-19"

[[trusted.errno]]
criteria = "safe-to-run"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2023-08-29"
end = "2027-02-19"

[[trusted.itoa]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2027-02-19"

[[trusted.js-sys]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2027-02-19"

[[trusted.libc]]
criteria = "safe-to-run"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2027-02-19"

[[trusted.linux-raw-sys]]
criteria = "safe-to-run"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2027-02-19"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2027-02-19"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2027-02-19"

[[trusted.quote]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-09"
end = "2027-02-19"

[[trusted.regex-syntax]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-30"
end = "2027-02-19"

[[trusted.rustix]]
criteria = "safe-to-run"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-10-29"
end = "2027-02-19"

[[trusted.rustversion]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-08"
end = "2027-02-19"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-28"
end = "2027-02-19"

[[trusted.slab]]
criteria = "safe-to-run"
user-id = 6741 # Alice Ryhl (Darksonn)
start = "2021-10-13"
end = "2027-02-19"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2027-02-19"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2027-02-19"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2027-02-19"

[[trusted.tokio]]
criteria = "safe-to-run"
user-id = 6741 # Alice Ryhl (Darksonn)
start = "2020-12-25"
end = "2027-02-19"

[[trusted.tokio-macros]]
criteria = "safe-to-run"
user-id = 6741 # Alice Ryhl (Darksonn)
start = "2020-10-26"
end = "2027-02-19"

[[trusted.tokio-stream]]
criteria = "safe-to-run"
user-id = 6741 # Alice Ryhl (Darksonn)
start = "2021-01-04"
end = "2027-02-19"

[[trusted.tracing-subscriber]]
criteria = "safe-to-deploy"
user-id = 10
start = "2025-08-29"
end = "2027-02-19"

[[trusted.unicode-ident]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2021-10-02"
end = "2027-02-19"

[[trusted.valuable]]
criteria = "safe-to-deploy"
user-id = 10
start = "2022-01-03"
end = "2027-02-19"

[[trusted.wait-timeout]]
criteria = "safe-to-run"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2025-02-03"
end = "2027-02-19"

[[trusted.wasm-bindgen]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2027-02-19"

[[trusted.wasm-bindgen-macro]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2027-02-19"

[[trusted.wasm-bindgen-macro-support]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2027-02-19"

[[trusted.wasm-bindgen-shared]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2027-02-19"

[[trusted.windows-link]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-07-17"
end = "2027-02-19"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2027-02-19"

[[trusted.zmij]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2025-12-18"
end = "2027-02-19"
